/*
 * SPDX-FileCopyrightText: 2024-2026 Anjishnu Nandi <https://github.com/cromaguy>
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

package chromahub.rhythm.app.util

/**
 * Filters raw commit messages into a clean, user-facing changelog.
 *
 * Mirrors the junk-commit filtering used by the release tooling
 * (scripts/prepare_release.py and scripts/generate_release_notes.py) so the
 * in-app "What's New" list shows the same meaningful entries as the fastlane
 * changelog and GitHub release notes: low-value commits (minor fixes,
 * lint/warning cleanups, workflow-file updates, version bumps, chore/CI noise)
 * are dropped, translation commits are collapsed into a single line, and
 * duplicate messages are removed.
 *
 * This targets commit-message-derived (nightly) changelogs and, as
 * defense-in-depth, release-body bullets. The stable/beta release-body
 * changelog is generated by scripts/generate_release_notes.py (which applies
 * the same filter upstream); [isJunkReleaseBullet] only guards against stray
 * or manually-authored entries.
 */
object ChangelogFilter {
    // Commit messages that carry no user-facing value and are excluded from changelogs
    private val JUNK_PATTERNS =
        listOf(
            Regex("^minor\\b.*$", RegexOption.IGNORE_CASE),
            Regex("^fix\\s+warnings?\\s*$", RegexOption.IGNORE_CASE),
            Regex("^fix\\s+lint\\s*$", RegexOption.IGNORE_CASE),
            Regex("^fix\\s+warnings?\\s*[/\\s-]?lint\\s*$", RegexOption.IGNORE_CASE),
            Regex("^update\\s+[a-z0-9_.-]+\\.(ya?ml|json|md|properties|txt)\\s*$", RegexOption.IGNORE_CASE),
            Regex("^update\\s+.*\\.github.*$", RegexOption.IGNORE_CASE),
            Regex("^bump\\s+(version|dependenc\\w+).*$", RegexOption.IGNORE_CASE),
            Regex("^cleanup\\s*$", RegexOption.IGNORE_CASE),
            Regex("^refactor\\s*$", RegexOption.IGNORE_CASE),
            Regex("^chore\\s*\\(\\s*(deps|ci|build|config)\\s*\\).*$", RegexOption.IGNORE_CASE),
            Regex("^(build|ci|chore|style|docs)\\s*:.*$", RegexOption.IGNORE_CASE),
        )

    private val TRANSLATION_PATTERN =
        Regex("l10n|translation|chore\\(l10n\\)|localiz|hardcoded.*strings", RegexOption.IGNORE_CASE)

    private val BOLD_CATEGORY_PREFIX = Regex("^\\*\\*[^*]+\\*\\*\\s*")
    private val LIST_BULLET_PREFIX = Regex("^[-*•]\\s*")

    /** Returns true when [msg] is a low-value commit that should not surface in the changelog. */
    fun isJunkCommit(msg: String): Boolean = JUNK_PATTERNS.any { it.containsMatchIn(msg) }

    /**
     * Defense-in-depth for release-body bullets: strips the list prefix and any
     * "**Category:**" prefix (e.g. "- **Added:** Minor fixes") before matching the
     * junk patterns, so low-value entries are dropped even if they slipped into
     * a release body.
     */
    fun isJunkReleaseBullet(bullet: String): Boolean {
        // Strip list bullets ("- ", "* ", "• ") and bold "**Category:**" prefixes.
        // They can appear in either order (e.g. "- **Added:** ..." or "**Fixed:** ..."),
        // and a single-char bullet strip must not eat a star of a leading "**", so
        // repeat until no prefix remains.
        var cleaned = bullet.trim()
        var previous: String
        do {
            previous = cleaned
            cleaned =
                cleaned
                    .replace(BOLD_CATEGORY_PREFIX, "") // "**Category:**" bold prefix
                    .replace(LIST_BULLET_PREFIX, "") // list bullet prefix
                    .trim()
        } while (cleaned != previous)
        return isJunkCommit(cleaned)
    }

    /**
     * Cleans raw commit-message lines into a deduplicated, user-facing changelog.
     *
     * Each line is trimmed and stripped of its list prefix, merge/release and
     * junk entries are dropped, all translation/localization commits are
     * collapsed into a single "Updated translations" line, and identical
     * messages are kept only once.
     */
    fun filterLines(lines: List<String>): List<String> {
        val result = mutableListOf<String>()
        val seen = mutableSetOf<String>()
        var hasTranslation = false
        for (rawLine in lines) {
            val msg =
                rawLine
                    .trim()
                    .removePrefix("-")
                    .removePrefix("*")
                    .removePrefix("•")
                    .trim()
            if (msg.isBlank()) continue
            if (msg.startsWith("Merge branch") || msg.startsWith("Merge pull request") || msg.startsWith("Release ")) continue
            if (isJunkCommit(msg)) continue
            if (TRANSLATION_PATTERN.containsMatchIn(msg)) {
                hasTranslation = true
                continue
            }
            if (!seen.add(msg)) continue
            result.add(msg)
        }
        if (hasTranslation) {
            result.add("Updated translations")
        }
        return result
    }
}
